include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unawaited_futures: false
